#!/usr/bin/python3

import sys


def open_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
    numbers = []
    for line in lines:
        numbers.append(int(line))
    return numbers


def factorize(n):
    for i in range(2, n):
        if n == ((n // i) * i):
            print("{}={}*{}".format(n, (n // i), i))
            break


def get_number(numbers_list):
    for i in numbers_list:
        factorize(i)


if len(sys.argv) == 2:
    get_number(open_file(sys.argv[1]))
else:
    print("Usage: python factors.py <file>")
    sys.exit(1)
